# FOR DEFINING THE NUMPY AS NP

In [ ]:
import numpy as np #for defining numpy as np

# NUMPY

In [ ]:
#printing the matrux
A=np.arange(1,13).reshape(4,3) #reshaping for 3 rows and 4 columns
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#printing a matrix with linspace
A=np.linspace(2,4,8).reshape(4,2)  #matrix with rows,columns,stepsize    reshaping with 4columns and 2 rows
print(A)

[[2.         2.28571429]
 [2.57142857 2.85714286]
 [3.14285714 3.42857143]
 [3.71428571 4.        ]]


In [ ]:
#printing the matrix
A=np.array([12,32,4,6,45,65,78,1]).reshape(2,2,2)
print(A)

[[[12 32]
  [ 4  6]]

 [[45 65]
  [78  1]]]


In [ ]:
#printing the matrix
B=np.array([45,67,89,12,34,51,90,98])
B.reshape(2,2,2)# because it wont change the changes because it take asa  before changes this is my thinking
                #reshape  - changes needs saving in another variable
print(B)

[45 67 89 12 34 51 90 98]


In [ ]:
#printing the matrix using resize
B=np.array([45,67,89,12,34,51,90,98])
B.resize(2,2,2) # resize changes the shape of original array
print(B)

[[[45 67]
  [89 12]]

 [[34 51]
  [90 98]]]


#ARRAY OPERATIONS

In [ ]:
#ARRAY OPERATIONS
A=np.array([23,45,76,1])
B=np.array([8,25,6,2])
C=A-B   #A list will throw an error while arrays iterate themselves
print(C)
print(A-B)

[15 20 70 -1]
[15 20 70 -1]


In [ ]:
#ARRAY OPERATIONS
A=np.array([23,45,76,1])
B=np.array([8,25,6,2])
C=A+B   #A list will throw an error while arrays iterate themselves
print(A+B)

[31 70 82  3]


In [ ]:
#Error printing by removing paranthesis
A=np.array[34,56,78,90]# BEACUSE OF AN ERROR AFTER REMOVING PARANTHSIS or list will throw an errior while arrays iterate themselves
B=np.array([7,9,3,12])
C=A-B
print(A-B)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
#Matrix multiplication by array operations by using symbol(*)
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
C=A*B   #one on one multiplication
print("___________________________")
print(C)

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
___________________________
[[ 184 1125]
 [ 456    2]]


In [ ]:
#Matrix multiplication by array operations by using symbol(@)
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
C=A@B   #matrix  multiplication or matrix multiplication for multiplication @
print("___________________________")
print(C)

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
___________________________
[[ 454  665]
 [ 614 1902]]


In [ ]:
#Matrix multiplication by array operations by using symbol(.-dot)
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
C=A.dot(B)   #for matrix  multiplication
print("___________________________")
print(C)

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
___________________________
[[ 454  665]
 [ 614 1902]]


In [ ]:
#Finding maximum and minimum of an array
A=np.array([12,43,5,12,98])
print(A.max())   #maximum
print(A.min())   #minimum,

98
5


In [ ]:
A=np.array(['34.2','56.7','78.2','90.9','90.8'])# maximum and minimum accepts only numeric datatypes ,int,float,it wont accepts string it shows error
print(A.max())
print(B.min())

UFuncTypeError: ufunc 'maximum' did not contain a loop with signature matching types (dtype('<U4'), dtype('<U4')) -> None

In [ ]:
A=np.array([12.45,43.567,5.43,12.789,98.89])  #it is floating points
print(A.max())     #maximum
print(A.min())     #minimum

98.89
5.43


In [ ]:
#print the maximum and minimum of array of row and column by axis
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print(B)
print("__________________")
print(A.max(axis=0)) #axis 0---column
print("__________________")
print(B.min(axis=1)) #axis 1----row


[[34 56]
 [78 90]]
[[ 7  9]
 [ 3 12]]
__________________
[78 90]
__________________
[7 3]


In [ ]:
#print the maximum of array of row and column by axis
A=np.array([23,45,98,101,456,12,4,123,86,90,453,2]).reshape(4,3)
print(A)
print("___________________________")
print(A.max(axis=0))    #axis 0 - column
print("___________________________")
print(A.max(axis=1))    #axis 1 -row

[[ 23  45  98]
 [101 456  12]
 [  4 123  86]
 [ 90 453   2]]
___________________________
[101 456  98]
___________________________
[ 98 456 123 453]


In [ ]:
#print the minimum of array of row and column by axis
A=np.array([23,45,98,101,456,12,4,123,86,90,453,2]).reshape(4,3)
print(A)
print("___________________________")
print(A.min(axis=0))    #axis 0 - column
print("___________________________")
print(A.min(axis=1))    #axis 1 -row

[[ 23  45  98]
 [101 456  12]
 [  4 123  86]
 [ 90 453   2]]
___________________________
[ 4 45  2]
___________________________
[23 12  4  2]


In [ ]:
#Joining arrays! and printing the vertically elements in stack
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
print("After vertical stacking the array is")    #vertical stack
print(np.vstack((A,B)))

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
After vertical stacking the array is
[[23 45]
 [76  1]
 [ 8 25]
 [ 6  2]]


In [ ]:
#Joining arrays! and printing the horizantally elements in stack
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
print("After horizontal stacking the array is")   #horizontal stack
print(np.hstack((A,B)))

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
After horizontal stacking the array is
[[23 45  8 25]
 [76  1  6  2]]


In [ ]:
# joining Arrays! and printing the vertically and horizantally elements in stack
A=np.array([34,56,78,90]).reshape(2,2)
B=np.array([7,9,3,12]).reshape(2,2)
print(A)
print("________________")
print(B)
print("after vertically stacking the arrays!")  #vertical stack
print(np.vstack((A,B)))
print("after horizontall stacking the arrays!") #horizontal stack
print(np.hstack((A,B)))

[[34 56]
 [78 90]]
________________
[[ 7  9]
 [ 3 12]]
after vertically stacking the arrays!
[[34 56]
 [78 90]
 [ 7  9]
 [ 3 12]]
after horizontall stacking the arrays!
[[34 56  7  9]
 [78 90  3 12]]


In [ ]:
#joining arrays stacking the elements by axis
A=np.array([23,45,76,1]).reshape(2,2)
B=np.array([8,25,6,2]).reshape(2,2)
print(A)
print("___________________________")
print(B)
print("After stacking the array is")
print(np.stack((A,B),axis=0))

[[23 45]
 [76  1]]
___________________________
[[ 8 25]
 [ 6  2]]
After stacking the array is
[[[23 45]
  [76  1]]

 [[ 8 25]
  [ 6  2]]]


In [ ]:
#joining arrays stacking the elements by ---> dstack
A=np.arange(30).reshape(2,3,5)   #groups,rows,columns here groups as the 2 types of 0to 29[[]]] rows as 0,5,10 and columns as 0,1,2,3,4
print(A)                         #stacks according to the dimension
print("After dstack")             #no of row == no.of groups
#no .of columns in every group == no.of rows in every group
#[0,0],[1,1],............
print(np.dstack(A))          # original   (groups,rows,columns)
                                #after dstack (columns,groups,rows)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays---->by vertically(vsplit)
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")    #splits the array vertically into equal halves
np.vsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays---->by vertically(vsplit)
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting arrays----->by vertically (vsplit)
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays----->by horizontally (hsplit)
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting")    #splits the array horizontally into equal halves
np.hsplit(A,3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
#splitting arrays----->by horizontally (hsplit)
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting")
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
#finding the maximum elements by argmax in the given array
A=np.array([12,54,77,2])
print(A)
print(A.argmax())           #argmax returns the position of the maximum element in the given array

[12 54 77  2]
2


In [ ]:
#finding the maximum elements by argmax in the given array
A=np.array([12,54,77,2])
print(A)
print(A.argmin())    #argmin returns the position of the minimum element in the given array

[12 54 77  2]
3


In [ ]:
#finding the minimum  element by argmax in the given array by the  axis
A=np.array([12,453,575,2,4,98,123,65,77,44,89,66]).reshape(4,3)
print(A)                 #  columns                rows
print(A.argmax(axis=0))  # 0  0     0            0   1   2
                         # 1   1     1           0   1   2
                         # 2   2     2           0   1   2
print(A.argmax(axis=1))

[[ 12 453 575]
 [  2   4  98]
 [123  65  77]
 [ 44  89  66]]
[2 0 0]
[2 2 0 1]


# STATISTICS

In [ ]:
#NUMPY STATISTICS
#mean ,medain,standard deviation,variance
A=np.array([12,34,56,78,89])
print("mean= ",np.mean(A))
print("median= ",np.median(A))
print("standard deviation= ",np.std(A))
print("variance= ",np.var(A))

mean=  53.8
median=  56.0
standard deviation=  28.173746644704533
variance=  793.76


# TRIGNOMETRY

In [ ]:
#TRIGNOMETRY
A=np.pi     #pi=180
print(A)    #radians

3.141592653589793


In [ ]:
#radian to degree conversion
np.rad2deg(A)     #radians to degree

180.0

In [ ]:
#finding the values of each one
A=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])       #radians
print(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
#finding the radian to degree
print(np.rad2deg(A))      #degree

[ 45.  60.  90. 180.]


In [ ]:
# finding the radians to the following array
C=np.array([0,30,45,60,90,120,180])
B=np.deg2rad(C)
print(B)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
#finding the sin values in radians
np.sin(C)   #sin

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
#finding the cos values in radians
np.cos(C)   #cos

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
#finding the tan values in radians
np.tan(C)


array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
#finding the sin^=cosecant
np.arcsin(1)        #sin^-1

1.5707963267948966

In [ ]:
#finding the cos^=secant
np.arccos(1)    #cos^-1

0.0

In [ ]:
#finding the tan^=cot
np.arctan(1)    #tan^-1

0.7853981633974483

# HYPOTENUSE

In [ ]:
#finding the hypotenuse
a=6
b=8
print(np.hypot(a,b))    #hypotenuse

10.0


SEARCHING AN ARRAY!

In [ ]:
#returns the position of the elements according to the condition  under the condition satisifies
A=np.array([12,45,2,67,23])
print(np.where(A>50)) #returns the position of the elements according to the condition

(array([3]),)


In [ ]:
#returns the position of the searching element in the array under the condition satisifies
A=np.array([12,45,2,67,23,45])
print(np.where(A==45))      #returns the position of the searching element

(array([1, 5]),)


In [ ]:
#returns the position of the even elements in the array if the condition satisifies
A=np.array([12,45,2,67,23,45])
print(np.where(A%2==0))      #returns the position of the even elements

(array([0, 2]),)


In [ ]:
#returns output the index of the seach element after sorting the list if it satisifies the condition
A=np.array([12,23,34,45,21,45])   #12 21 23 34 45 45
print(np.searchsorted(A,34))      #output the index of the seach element after sorting the list

2


# LINEAR ALGEBRA

In [ ]:
#linear algebra
A=np.array([6,34,2,67,8])
B=np.array([5,12,4,1,3])
print(np.add(A,B))                #addition of 2 arrays
print(np.subtract(A,B))           #subtraction of 2 arrays

[11 46  6 68 11]
[ 1 22 -2 66  5]


In [ ]:
#quotient
print(np.divide(A,B))       #quotient

[ 1.2         2.83333333  0.5        67.          2.66666667]


In [ ]:
#remainder
print(np.mod(A,B))        #remainder

[ 1 10  2  0  2]


In [ ]:
#multiplication
print(np.multiply(A,B)) #multiplication

[ 30 408   8  67  24]


In [ ]:
## both quotient and remainder(divmod)
print(np.divmod(A,B))     # both quotient and remainder

(array([ 1,  2,  0, 67,  2]), array([ 1, 10,  2,  0,  2]))


In [ ]:
#difference between two elements
A=np.array([6,34,2,67,8])
print(np.diff(A))      #difference between two elements

[ 28 -32  65 -59]


In [ ]:
#sort
A=np.array([6,34,2,67,8])
print(np.sort(A))

[ 2  6  8 34 67]


# SET FUNCTIONS

In [ ]:
#set functions
A=np.array([6,34,2,67,8])
B=np.array([5,12,4,1,3])
print(np.union1d(A,B))

[ 1  2  3  4  5  6  8 12 34 67]


In [ ]:
#Intersection
A=np.array([6,34,2,67,8])
B=np.array([5,12,4,1,2,3])
print(np.intersect1d(A,B))

[2]


In [ ]:
#Set difference
A=np.array([6,34,2,67,8,12])
B=np.array([5,12,4,1,3])
print(np.setdiff1d(A,B)) #it prints no common elements

[ 2  6  8 34 67]


ROUNDING!

In [ ]:
#Rounding!
print(np.trunc([-3.11234,4.235767]))

[-3.  4.]


In [ ]:
#floor
print(np.floor([-3.11234,4.235767]))

[-4.  4.]


In [ ]:
#ceil
print(np.ceil([-3.11234,4.235767]))

[-3.  5.]


In [ ]:
#fix
print(np.fix([-3.11234,4.235767]))

[-3.  4.]


In [ ]:
#round
a=np.around(-3.11234, 3)
print(a)

-3.112


# MORE FUNCTIONS

In [ ]:
#more functions
#cumulative sum
A=np.array([3,4,12,45,67])      #cumulative sum
print(np.cumsum(A))

[  3   7  19  64 131]


In [ ]:
#cumulative product
A=np.array([3,4,12,45,67])      #cumulative product
print(np.cumprod(A))

[     3     12    144   6480 434160]


In [ ]:
#Finding lcm and gcd of a number
print(np.lcm(48,6))     #lcm
print(np.gcd(48,6))     #gcd

48
6


In [ ]:
#finding lcd and gcd of array
Ar=np.array([24,45,23])
print(np.lcm.reduce(Ar))    #lcm for array of elements using reduce
print(np.gcd.reduce(Ar))    #gcd for array of elements using reduce

8280
1


In [ ]:
#inverse of the matrix
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


# RANDOM FUNCTION

In [ ]:
from numpy import random as rd   #for defining numpy as np

In [ ]:
#printing a random number from limit
A=rd.rand() #n #default limit 0 to 0.99
print(A)

0.5338806938804723


In [ ]:
#displays 10 numbers from range
print(rd.rand(10))    # displays the 10 random numbers with the range 0 to 0.99

[0.017916   0.0631613  0.18980189 0.34374585 0.68532408 0.75219564
 0.84004001 0.87511699 0.63482009 0.46562119]


In [ ]:
#printing the numbers from range randomly
A=rd.randint(4) #randint(limit)==> limit 0,1,2,3,4
print(A)

0


In [ ]:
#printing the numbers randomly in the range with step size
A=rd.randint(50,size=6) #limit with size
print(A)

[41 21 40 44 10 18]


In [ ]:
#printing the numbers randomly in the range with shape,size
A=rd.randint(50,size=(2,3)) #limit with shape
print(A)

[[39 41 47]
 [44  9 37]]


In [ ]:
#Joins and add the inner loop
A=np.array([1,2,3])
B=np.array([4,5,6])
# 1*4 +2*5 +3*6
print(np.inner(A,B))

32


In [ ]:
#Joins
A=np.array([1,2,3])
B=np.array([4,5,6])
# 1X(4,5,6)+2(4,5,6)+3(4,5,6)
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
#Joins
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.cross(A,B))   #here det and 1st column wont be included other to be cross(multiplied)

[-3  6 -3]
