# STRING

In [ ]:
#Variable
a=10
print("I am", a, "years old ")

I am 10 years old 


# ARITHMETIC OPERATIONS

In [ ]:
#Arithmetic operations on two integer variables
a=int(input("Enter a: "))
b=int(input("Enter b: "))
print("Sum is :",a+b)
print("Difference is :",a-b)
print("Product is :",a*b)
print("Quotient is :",a/b)
print("Remainder is :",a%b)
print("Power is :",a**b)
print("Floor division is :",a//b)

Enter a: 32
Enter b: 7
Sum is : 39
Difference is : 25
Product is : 224
Quotient is : 4.571428571428571
Remainder is : 4
Power is : 34359738368
Floor division is : 4


# CONTROL STRUCTURES

In [ ]:
#Take a salary from user,if the salary is more than 50000 there is 10% tax print his final salary
s=int(input("enter salary"))
if(s>=50000):
  s-=s*(0.1)
  print("final salary is: ",s)
else:
  print("there is no tax deduction")

enter salary75000
final salary is:  67500.0


In [ ]:
#Get the salary from the user if the salaryis more than or equal to 50k apply 10% tax deduction,if the salary is less than 50k apply 5% tax,if the salary is more than 70k apply 12% tax, if salary exceeds 100k print you are promoted to next level
s=int(input("enter salary"))
if s==0:
  print("enter valid salary")
elif(s<50000):
  print("Salary is: ",s-s*(0.05))
elif(s<=70000):
  print("Salary is: ",s-s*(0.1))
elif(s<=100000):
  print("Salary is: ",s-s*(0.12))
else:
  print("you are promoted")

enter salary200000
you are promoted


# LOOPS OF RANGE FUNCTION

In [ ]:
#Range of a number displaying
ran=range(1,11)
for i in ran:
    print(i)


1
2
3
4
5
6
7
8
9
10


In [ ]:
#Range of a number displaying
#If we got an error then import range function
from builtins import range
ran=range(1,11)
for i in ran:
    print(i)


1
2
3
4
5
6
7
8
9
10


In [ ]:
#for loop
r=range(1,11)
n=int(input("enter number: "))
for i in r:
  print(n,"x",i,"=",i*n)

enter number: 101
101 x 1 = 101
101 x 2 = 202
101 x 3 = 303
101 x 4 = 404
101 x 5 = 505
101 x 6 = 606
101 x 7 = 707
101 x 8 = 808
101 x 9 = 909
101 x 10 = 1010


In [ ]:
#while loop
n=int(input("enter n"))
i=1
while(i<11):
   print(n,"x",i,"=",i*n)
   i+=1

enter n45
45 x 1 = 45
45 x 2 = 90
45 x 3 = 135
45 x 4 = 180
45 x 5 = 225
45 x 6 = 270
45 x 7 = 315
45 x 8 = 360
45 x 9 = 405
45 x 10 = 450


# LISTS

In [ ]:
#creating a list
l=['Sam','Sowshi',1,10.1,'@']
for i in l:
  print(i)

Sam
Sowshi
1
10.1
@


In [ ]:
#list heterogeneous
l1=[1,2.5,"apple",True]
print(l1[::1])

[1, 2.5, 'apple', True]


In [ ]:
#list heterogeneous
l1=[1,2.5,"apple",True]
print(l1[0:5:1])

[1, 2.5, 'apple', True]


In [ ]:
#combine the 2 lists by zip function
l1=[1,23,45]
l2=["ramya","likhita","lav"]
z=zip(l1,l2)
for i in z:
  print(i)


(1, 'ramya')
(23, 'likhita')
(45, 'lav')


In [ ]:
#Mutuable(Appending and Inserting)
l1.append('a')     #list name.append(element)-->adds elements at the back of the list
print(l1)
l1.insert(4,"hi")  #listname.insert(index,element)-->inserts element "hi" in the index 4
print(l1)



[1, 23, 45, 'a']
[1, 23, 45, 'a', 'hi']


In [ ]:
#adding 2 lists
l2=['&','@',123,"mango"]
l1.extend(l2)       #list1.extend(list2)--->l1=l1+l2
print(l1)

[1, 23, 45, 'a', 'hi', '&', '@', 123, 'mango']


In [ ]:
#remove
l1.remove('@')   #list name.remove(element)-->removes the given element in list l1
l1.pop(3)        #list name.pop(index)-->pops the element which is at index given in list l1
print(l1)

[1, 23, 45, 123, 'mango']


In [ ]:
#clear
l1.clear() #listname.clear()--->clears the list and it prints empty
print(l1)

[]


In [ ]:
#create a list of 10 integer elements print their squares save these squares in new list
l=[1,10,12,345,23,67,123,78,988,86]
l2=[]
for i in l:
  l2.append(i**2)
print(l2) #we give indentation for this then it prints like the matrix so we should not give the indentation

[1, 100, 144, 119025, 529, 4489, 15129, 6084, 976144, 7396]


# LIST COMPREHENSION

In [ ]:
#list comprehension
#newlist=[output for if] without condition
l1=[1,10,12,345,23,67,123,78,988,86]
l2=[i*i for i in l1]
print(l2)

[1, 100, 144, 119025, 529, 4489, 15129, 6084, 976144, 7396]


In [ ]:
#list comprehension
#newlist=[output for if]
l1=[1,10,12,345,23,67,123,78,988,86]
l2=[i*i for i in l1 if i>50]
print(l2)

[119025, 4489, 15129, 6084, 976144, 7396]


In [ ]:
#list comprehension
#newlist=[(st of if) if (cond) else (st of else) for]
l1=[1,10,12,345,23,67,123,78,988,86]
l2=[i*i if i>50 else 'x' for i in l1]
print(l2)




['x', 'x', 'x', 119025, 'x', 4489, 15129, 6084, 976144, 7396]


In [ ]:
#take the salary from the user if salary is less than 50k apply 10% tax otherwise 15% tax
s=int(input("enter salary"))
l=[s-(s*0.1) if (s<=50000) else (s-(s*15)/100)]
print(l)

enter salary65000
[55250.0]


In [ ]:
#take the salary ,if salary is less than 50k apply 10% tax otherwise 15% tax
l1=[55000,75000,10000,90000]
l=[n-(n*0.1) if(n<=50000) else n-(n*0.15)for n in l1]
print(l)

[46750.0, 63750.0, 9000.0, 76500.0]


# DICTIONARIES

In [ ]:
#create a dictionary  #dictname={key:val,key:val,...........}
dict1={"mentor":'jwalitha',"mentor":'likitha',35:'ramya',36:'lavanya',71:'dhanush'}
print(dict1)

{'mentor': 'likitha', 35: 'ramya', 36: 'lavanya', 71: 'dhanush'}


In [ ]:
#accessing keys and values from dictionary
dict1={"mentor":'jwalitha',"mentor":'likitha',35:'ramya',36:'lavanya',71:'dhanush'}
print(dict1.keys())    #accessing keys
print(dict1.values())  #accessing values
print(dict1[36])       #accessing particular value

dict_keys(['mentor', 35, 36, 71])
dict_values(['likitha', 'ramya', 'lavanya', 'dhanush'])
lavanya


In [ ]:
#nested dictionary
dict3={"dept":"CSE","detailes":{"year":"II","sec":"D","count":71}}
print("year is ",dict3["detailes"]["year"])
print("section is ",dict3["detailes"]["sec"])
print("count is ",dict3["detailes"]["count"])

year is  II
section is  D
count is  71
{'dept': 'CSE', 'detailes': {'year': 'II', 'sec': 'D', 'count': 71}}


In [ ]:
#combine the 2 lists by zip function
l1=[23,9,15,30]
l2=["Samyuktha","Sowshya","Ram","Sirish"]
z=zip(l1,l2)
for i in z:
  print(i)

(23, 'Samyuktha')
(9, 'Sowshya')
(15, 'Ram')
(30, 'Sirish')


In [ ]:
#creates a dictionary from two lists by using zip function
l1=[23,9,15,30]
l2=["Samyuktha","Sowshya","Ram","Sirish"]
print(dict(zip(l1,l2)))

{23: 'Samyuktha', 9: 'Sowshya', 15: 'Ram', 30: 'Sirish'}


In [ ]:
#creating dictionaries using dict of zip and directly convert it if getting error
from builtins import dict
l1=[23,9,15,30]
l2=["Samyuktha","Sowshya","Ram","Sirish"]
print(dict(zip(l1,l2)))

{23: 'Samyuktha', 9: 'Sowshya', 15: 'Ram', 30: 'Sirish'}


# NUMPY

In [ ]:
#importing the function
import numpy as np

In [ ]:
#numpy #creating a 1-dimensional array
import numpy as np
A=np.array([1,2,3,4])  #1-d array
print(A.ndim)          #(columns,) or n dimension
print(A.shape)         #shape means how many rows and columns

1
(4,)


In [ ]:
#numpy #creating a 2-dimensional array
import numpy as np
B=np.array([[1,2,3,4],[5,6,7,8]])   #2-d array
#elements in each row=columns
print(B)
print(B.ndim)    #2-d array
print(B.shape)   #(rows,columns)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [ ]:
#numpy #creating a 3-dimensional array
C=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[56,76,6]]])  #3-d array
print(C)
print(C.ndim)  #3-d array
print(C.shape) #(groups,rows,columns)  #no.of.elements=group*rows*columns

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [56 76  6]]]
3
(2, 2, 3)


In [ ]:
#for ones when 2 rows and 3 columns
m=np.ones((2,3)) #r,c
print(m)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#for ones when 3 rows and 4 columns and step size 3
m=np.ones((3,4,3))  #g,r,c
print(m)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#for zeros
m=np.zeros((3,4,3))  #g,r,c
print(m)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#creating identity matrix
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#creating a range of a matrix
A=np.arange(1,10)   #start,stop
print(A)
print(type(A))  #for type of dimensional array 1or2or3

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
#creating a range of a matrix
A=np.arange(1,10,2)   #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using a range function between 1 and 1000
A=np.arange(8,1001,8)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#linspace--->splitting a range into n numbers with coomon differences
A=np.linspace(48,58,11)    #start ending equal parts or common difference
print(A)

[48. 49. 50. 51. 52. 53. 54. 55. 56. 57. 58.]


In [ ]:
#linspace--->splitting a range into n numbers with coomon differences
A=np.linspace(2,3,12)    #start ending equal parts or common difference
print(A)

[2.         2.09090909 2.18181818 2.27272727 2.36363636 2.45454545
 2.54545455 2.63636364 2.72727273 2.81818182 2.90909091 3.        ]


HOME TASK -
# Study Tuples and Sets
and do qrcodes and documentation for team lead


# TUPLES

In [ ]:
#Displaying the tuple elements
t=(12,43,6.45,"apple")
for i in t:             #display elements in the tuples using loop
  print(i)

12
43
6.45
apple


In [ ]:
#Tuple slicing
print(t)        #original array
print(t[::-1])  #tuple slicing

(12, 43, 6.45, 'apple')
('apple', 6.45, 43, 12)


In [ ]:
#Sort and pop
t1=(21,56,4,23,89)
s=sorted(t1) #sort in the order(sorted)
print(s)
s.pop()  #pops the last element(pop)
print(s)

[4, 21, 23, 56, 89]
[4, 21, 23, 56]


In [ ]:
#conversion of list to tuple
l=[1,23,4,5,6,7]
print(l)          #list
print(tuple(l))   #tuple

[1, 23, 4, 5, 6, 7]
(1, 23, 4, 5, 6, 7)


In [ ]:
#combining of tuple by using zip function
z=zip(t1,l)
print(tuple(z))

((21, 1), (56, 23), (4, 4), (23, 5), (89, 6))


In [ ]:
#concatination of two tuples
print(t+t)

(12, 43, 6.45, 'apple', 12, 43, 6.45, 'apple')


In [ ]:
#Combining two tuples
t1=(1,2,3,4)
t2=(5,6,7,8)
t3=t1+t2
print(t3)

(1, 2, 3, 4, 5, 6, 7, 8)


In [ ]:
#index of a tuple element
print(t3.index(8))

7


In [ ]:
#count of a element
t=(1,23,55,67,88,99,22,23,55)
print(t.count(23))

2


In [ ]:
#deleting a tuple
tuple=(9,10,11,12)
del tuple
print(tuple)

<class 'tuple'>


In [ ]:
#length of a tuple element
print(len(t3))

8


In [ ]:
#printing 5 times of a tuple
print(t3*5)

(1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8)


In [ ]:
# finding the t1 is greater or t2 is greater
print(t1>t2)

True


In [ ]:
#maximum and minimum of a tuple
print(max(t))   #maximum element
print(min(t))   #minimum element

99
1


In [ ]:
#tuple comprehension
t=(1,23,55,67,88,99,22,23,55)
l=[i for i in t if i%11==0]
print(tuple(l))

(55, 88, 99, 22, 55)


# SETS

In [ ]:
#Displaying set elements
s1={1,23,45,1,23,67,89}    #prints the unique elements in set
print(s1)

{1, 67, 23, 89, 45}


In [ ]:
#union
s2={1,23,1,67,89}
print(s1.union(s2))  #union--prints only the unique elements that means the repeated and non repeated elements print only once

{1, 67, 45, 23, 89}


In [ ]:
#Intersection
print(s2.intersection(s1))  #Intersection--prints only the intersection elements that means that only repeated elements print

{89, 67, 1, 23}


In [ ]:
#Difference
print(s1.difference(s2))    #difference-->prints only the non repeated elements wont comethat means 45 is not repeated so it prints

{45}


In [ ]:
#length of a set
s={1,2,3,4,5}
print(len(s))

5


In [ ]:
#minimum and maximum of a set
print(min(s))   #minimum of a element in a set
print(max(s))   #maximum of a element in a set

1
5


In [ ]:
#Sum of a set
print(sum(s))  #1+2+3+4+5

15


In [ ]:
#to sort a set if a set is unsorted
s3={5,3,2,4,1}   #unordered set
print(sorted(s3))

[1, 2, 3, 4, 5]


In [ ]:
#updation of a set s1 into s2
s1.update(s2)
print(s1)

{1, 67, 45, 23, 89}


In [ ]:
#adding the element into set
s1.add(89)
print(s1)

{1, 67, 234, 45, 23, 89}


In [ ]:
#removing an element in a set
s1.remove(45) #removes a particular element in a set
print(s1)

{1, 67, 234, 23, 89}


In [ ]:
#pop the element in a set
s1.pop()
print(s1) #removes an element in a set randomly or left or right without giving an element or index

{1, 67}
